version: '3.8'

services:

  etcd:
    image: quay.io/coreos/etcd:v3.5.16
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./etcd:/etcd
    command:
      - etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --data-dir=/etcd
    ports:

      - "2379:2379"


  minio:
    image: minio/minio:latest
    container_name: milvus-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    volumes:
      - ./minio:/data

    command:
      - server
      - /data


  milvus:
    image: milvusdb/milvus:v2.6.13
    container_name: milvus_standalone

    depends_on:
      - etcd
      - minio

    ports:
      - "19530:19530"
      - "9091:9091"

    environment:
      ETCD_ENDPOINTS: etcd:2379

      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin


    volumes:
      - ./data:/var/lib/milvus

    command:
      - milvus
      - run
      - standalone



